os: linux
dist: bionic
language: c

matrix:
  include:
    # Linux - amd64
    - env: BRANCH=1.2.6
    - env: BRANCH=devel

    # Linux - arm64
    - arch: arm64
      env: BRANCH=1.2.6

    # Linux - ppc64
    - arch: ppc64le
      env: BRANCH=1.2.6

    # macOS - amd64
    - os: osx
      env: BRANCH=1.2.4

    # windows - amd64
    - os: windows
      env: BRANCH=1.2.4
    - os: windows
      env: BRANCH=devel

cache:
  directories:
    - "$HOME/.choosenim"
    - "$HOME/Nim"

install:
  - curl https://gist.github.com/elijahr/a72a228b9617b759a1c24062d35cc23d/raw/2c10bab287e6865b0c63d1d008a0038c7c3c5d4c/travis.sh -LsSf -o travis.sh
  - source travis.sh

script:
  - nimble develop -y
  - nimble test
